#+BEGIN_COMMENT
.. title: Tealdeer Pages
.. slug: tealdeer-pages
.. date: 2025-05-30 11:43:01 UTC-07:00
.. tags: tealdeer
.. category: Tealdeer
.. link: 
.. description: Pages for tealdeer.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

This is for configuring [[https://tealdeer-rs.github.io/tealdeer/][tealdeer]], a command-line help system.

- The expected folder in this repository to put these pages is ~dingehaufen/tealdeer/pages/~.
- The default location that ~tealdeer~ will look for the pages is $~/.local/share/tealdeer/pages/~$ so maybe symlink it there.
- The pages that come with ~tealdeer~ are at $~/.cache/tealdeer/tldr-pages/pages/$ (look here for examples)

* Patches
These are [[https://tealdeer-rs.github.io/tealdeer/usage_custom_pages.html#custom-patches][patches]] which extend existing help pages rather than replacing them. If you want to add a new command or replace the existing tealdeer help you would use [[https://tealdeer-rs.github.io/tealdeer/usage_custom_pages.html#custom-pages][pages]] instead (they go in the same folder, there's just a different file-name convention).

** Screen

#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/screen.patch.md :exports none
<<screen-name>>
#+end_src

*** Name the Screen

#+begin_src md :noweb-ref screen-name
- Give the screen a name

`<Ctrl-a> A`
#+end_src

** Ghostscript (gs)
This is for ghost script.

#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/gs.patch.md :exports none
<<gs-black-and-white-pdf>>

<<gs-compress-ebook>>
#+end_src

*** Black and White PDF

This is to convert a PDF's text and vector images to Black and White to make it easier to read when printed. From a [[https://askubuntu.com/a/1474303][Ask Ubunt (Stack Exchange)]] answer.

#+begin_notecard
In the cases I've tried this doesn't convert raster images.
#+end_notecard

#+begin_src markdown :noweb-ref gs-black-and-white-pdf
- Convert PDF text to black and white (not grayscale)

`gs -sDEVICE=pdfwrite -dBlackText -dBlackVector -dNOPAUSE -dBATCH -sOutputFile={{output-file-name}} {{pdf-input-file-name}}`
#+end_src

*** Compress For Ebook

This adds some extra flags to the compression help that comes with tealdeer. 

#+begin_src markdown :noweb-ref gs-compress-ebook
- Reduce PDF File Size, possibly more than the version up above

`gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -dDetectDuplicateImages -dCompressFonts=true -sOutputFile={{output-file-name}} {{input-file-name}}`
#+end_src

- See : [[https://ghostscript.com/blog/optimizing-pdfs.html][Optimizing PDFs]] - From the Ghostscript Blog. This notes that DetectDuplicateImages is actually on by default so you only need to use it if you want to turn it off, but I didn't read that until after using it. It might make sense to experiment with it on and off. The same might go for the CompatibilityLevel.

** Virtual Fish

#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/vf.patch.md :exports none
<<vf-list>>

<<vf-rebuild>>

<<vf-rebuild-another>>
#+end_src

*** Check The Environment

This adds the build-state for the virtual-environments managed by virtualfish.

#+begin_src markdown :noweb-ref vf-list
- List Environments and the Current State (do they need to be rebuilt?):

`vf ls --details`
#+end_src

*** Rebuild the Environment

This is the command to use after an Ubuntu upgrade where they change the python version and all the virtual environments are broken.

#+begin_src markdown :noweb-ref vf-rebuild
- Rebuild the current environment (e.g. after Ubuntu changes pip):

`vf upgrade --rebuild`
#+end_src

You can also rebuild a specific environment (not necessarily the one you're in).

#+begin_src markdown :noweb-ref vf-rebuild-another
- Rebuild a specific environment

`vf upgrade --rebuild {{virtualenv-name}}`
#+end_src

#+begin_notecard
If the environments are broken by an update, ~pipx~ is likely broken too, run this too, maybe:

 - ~pipx reinstall-all~
 - ~pip install setuptools --upgrade~
#+end_notecard

** pdfjam

#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/pdfjam.patch.md :exports none
<<pdfjam-letter-size>>
#+end_src

*** Resize to Letter

#+begin_src markdown :noweb-ref pdfjam-letter-size
- Resize PDF document to letter-paper size

`pdfjam {{input-file}} --paper letter --outfile {{output-file-name}}`

`pdfjam {{input-file}} --papersize 8.5in,11in --outfile {{output-file-name}}`
#+end_src

** Emacs
#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/emacs.patch.md :exports none
<<emacs-sudo-file>>

<<emacs-init-directory>>
#+end_src

*** Open File With Sudo
Got this from [[https://stackoverflow.com/questions/95631/open-a-file-with-su-sudo-inside-emacs][a Stack Overflow Question]]. The user's question is asking for an alternative way to do this, but the answers tell him that it's the best way to do it after all (he thought it was using SSH but it uses a sub-shell).

#+begin_src markdown :noweb-ref emacs-sudo-file
- Open a (local) file with sudo.

`C-x C-f /sudo::/path/to/file`
#+end_src

*** Use a Different Init.el
This is to use a different ~init.el~ file (presumably for debugging).

#+begin_src markdown :noweb-ref emacs-init-directory
- Use a different initialization file when starting up:

`emacs --init-directory={{path/to/directory-with-init/}}`
#+end_src

** Image Magick
#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/magick-convert.patch.md :exports none
<<magick-remove-background>>
#+end_src

*** Remove PDF Background
This assumes a image "density" for the background and converts the pages to images so the output file will likely be much larger. It might be best to use this for printing and then deleting the converted PDF.

#+begin_src markdown :noweb-ref magick-remove-background
- Remove background of PDF assuming the image density

`magick convert -density 300 {{path/to/input.pdf}} -white-threshold 80% {{path/to/output.pdf}}`
#+end_src

#+begin_notecard
I also tried removing the background color specifically but doing that eats into everything that sits above the background as well (removes the anti-aliasing overlap, I assume).
#+end_notecard

* Pages

These are [[https://tealdeer-rs.github.io/tealdeer/usage_custom_pages.html#custom-pages][pages]] - whatever you put in a page file will be the starting point for the tealdeer entry - these will either start a new tealdeer entry or will clobber any exsting one that came with tealdeer. The thing that tells tealdeer that it's a page and not a patch is that the filename ends with ~page.md~ instead of ~patch.md~. Otherwise the contents look the same.

** MakeMKV Command Line

The ~makemkvcon~ command has a ~--help~ output, which is somewhat vague. I got the information for this from a developers text file [[https://www.makemkv.com/developers/usage.txt][usage.txt]] on makemkv.com/developers. Normally I use the GUI but sometimes it crashes due errors specific to the GUI so the command line interface is useful to work around those cases.

#+begin_src noweb :tangle ../dingehaufen/tealdeer/pages/makemkvcon.page.md :exports none
# makemkvcon

> Command-line interface for MakeMKV (https://www.makemkv.com/)

<<list-devices>>

<<save-mkvs>>
#+end_src

*** List Drives

This lists the drives as ~makemkvcon~ sees them.

 - ~--robot~: meant for automation, tells the program to output the information to the screen
 - ~--cache=1~: reduce the cache size (optional)
 - ~info~: the sub-command to print information
 - ~disc:9999~: show discs (not files, etc.)

#+begin_src markdown :noweb-ref list-devices
- List drives - DRV:index,visible,enabled,flags,drive name,disc name

`makemkvcon --robot --cache=1 info disc:9999`
#+end_src

The output looks something like:

#+begin_src sh
MSG:1005,0,1,"MakeMKV v1.18.2 linux(x64-release) started","%1 started","MakeMKV v1.18.2 linux(x64-release)"
DRV:0,2,999,1,"DVD+R-DL HL-DT-ST DVDRAM GSA-T50N RQ01 KWF9AEJ1028","MAD_MAX_FURY_ROAD","/dev/sr0"
#+end_src

With more lines below it. The second line is the one I'm interested in. It has the format:

`DRV:index,visible,enabled,flags,drive name,disc name`

This table shows what their text file says the fields mean.

| Field      | Description                                   |
|------------+-----------------------------------------------|
| DRV        | This is a drive                               |
| index      | The number we'll use to refer to the drive    |
| visible    | 1 if drive is present                         |
| enabled    | 1 if drive is accessible                      |
| flags      | media flags (see AP_DskFsFlagXXX in apdefs.h) |
| drive name | drive name string                             |
| disc name  | disc name string                              |

Looking at the sample output, it would appear that the drive isn't present or accessible, which doesn't seem right so I just ignore everything but the ~drive name~ to find the right entry in the output and the ~index~ for use in invoking ~makemkvcon~.

*** Copy Disc As MKV Files

#+begin_src markdown :noweb-ref save-mkvs
- Save disk to the current directory as MKV files

`makemkvcon mkv disc:{{index}} all .`

- Save disk to another directory as MKV files

`makemkvcon mkv disc:{{index}} all {{/absolute-path-to-folder/}}`
#+end_src

The sample shows the output being copied to `c:\folder` which is a DOS format (I think). It didn't seem to work when I used a relative path (other than the current directory) so I assume you need to use the full path starting from ~/home/~.
