#+BEGIN_COMMENT
.. title: config.fish The Fish Configuration
.. slug: configfish-the-fish-configuration
.. date: 2023-06-22 13:14:19 UTC-07:00
.. tags: configuration
.. category: Configuration
.. link: 
.. description: The fish configuration file.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

#+begin_src sh :tangle ../dingehaufen/config.fish :exports none
<<emacs-environment>>

<<environment>>

<<most-pager>>      
# path additions moved to extra_paths.fish

  # waiting for proton-vpn to get this working again.
# <<vpn>>
#+end_src

This is the fish configuration file. It goes into ~~/.config/fish/config.fish~.

* Environment Variables

The ~--export~ flag exports the shell variable to child processes, making it an "environment variable".

** Emacs

Sets us up to use the emacs client as the default editor.

- ~--create-frame~ tells emacs to create a new frame instead of continuing in the current one (if it's already open).
- ~--alternate-editor~: what to fall back to if the emacs-client server isn't running.
  
#+begin_src fish :noweb-ref emacs-environment
set --export ALTERNATE_EDITOR ""
set --export EDITOR "emacsclient --create-frame"
set --export VISUAL "emacsclient --create-frame --alternate-editor emacs"
#+end_src

** The Rest

#+begin_src fish :noweb-ref environment
# for extra docker build features (like smarter pip caching)
set --export DOCKER_BUILDKIT 1

# R Downloads
set --export R_LIBS ~/.local/lib/R/library/
#+end_src

** The Most Pager

The [[https://en.wikipedia.org/wiki/Most_(Unix)?useskin=vector][most pager]] is a slightly fancier version of ~less~ and ~more~. Setting it as the default pager will cause programs that use pagers (like ~man~) to use it.

#+begin_src fish :noweb-ref most-pager
# use the most pager instead of less
set -x PAGER most
#+end_src
* Proton VPN

The current command-line interface is deprecated so it gets uninstalled when you install the GUI, but the GUI was having problems so I uninstalled it and went back to using the CLI, but depending on what is installed this may or may not work (and it is kind of slow so it may not be a good idea anyway). Everytime you open a shell this will run (e.g. a byobu window or SSH session).

#+begin_src fish :noweb-ref vpn
# check the vpn (requires the installation of the proton-vpn command-line command)
if status --is-interactive
  protonvpn-cli status
end
#+end_src

#+begin_notecard
I went back to using the GUI to test some things out... hopefully they'll get the CLI working again, but for now (2024-12-29) no CLI.
#+end_notecard
