#+BEGIN_COMMENT
.. title: Random Choices
.. slug: random-choices
.. date: 2024-08-19 12:19:35 UTC-07:00
.. tags: fish, configuration
.. category: Configuration
.. link: 
.. description: The random-choices abbreviations.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

#+begin_src sh :tangle ../dingehaufen/conf.d/choices.fish :exports none
<<random-word>>

<<random-motif>>

<<random-imdb-movie>>
#+end_src
* Random Word

This selects a random word from a file created by grepping the Gutenberg unabridged Webster's dictionary.

#+begin_src fish :noweb-ref random-word
abbr --add -- word "random choice (cat ~/.local/share/choice/words.txt)"
#+end_src

The ~words.txt~ file was created from the =~/pCloud/synced/reading/423-websters-unabridged-dictionary/websters-unabridged-dictionary-project-gutenberg.txt= using grep.

#+begin_src fish
grep -P "[A-Z][A-Z]+" <file> > words.txt
#+end_src

This relies on the fact that words being defined are in all-caps. It ends up catching more than just the words but I figure I'll update it as I find the other cases.

* Random Motif

This selects a random motif from the [[https://en.wikipedia.org/wiki/Motif-Index_of_Folk-Literature?useskin=vector][Motif-Index of Folk Literature]]. The file came from [[https://archive.org/details/Thompson2016MotifIndex][archive.org]] (the searchable text version).

#+begin_src fish :noweb-ref random-motif
abbr --add -- motif "zcat \
    ~/.local/share/choice/motif-index.txt.gz | shuf -n1"
#+end_src

The ~words.txt~ file was created from the =~/pCloud/synced/reading/423-websters-unabridged-dictionary/websters-unabridged-dictionary-project-gutenberg.txt= using grep.

#+begin_src fish
grep -P "[A-Z][A-Z]+" <file> > words.txt
#+end_src

This relies on the fact that words being defined are in all-caps. It ends up catching more than just the words but I figure I'll update it as I find the other cases.

- [[https://stackoverflow.com/a/8151437][Stackoverflow on using gzip to extract lines]]
- [[https://unix.stackexchange.com/a/683295][Stack Exchange on extracting one line]]

#+begin_notecard
**Note:** Using 'gzip' worked for this, but when I tried it on a bigger file it gave an error (too many responses) so I think it isn't the best way to do it. Using 'zcat' works even with really big files.
#+end_notecard

* Random IMDB Movie

#+begin_src fish :noweb-ref random-imdb-movie
abbr --add -- imdb "zcat /media/irvin/datasets/imdb/movie.basics.tsv.gz | shuf -n1"
#+end_src
