#+BEGIN_COMMENT
.. title: Rsync Functions
.. slug: rsync-functions
.. date: 2026-09-17 21:54:32 UTC-07:00
.. tags: rsync,function
.. category: Function
.. link: 
.. description: Rsync Functions
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

#+begin_src noweb :tangle ../functions/rsyncer.fish
<<rsyncer-function>>
#+end_src

#+begin_src nowe :tangle ../functions/rsyncerd.fish
# <<rsyncerd-function>>
#+end_src

* Rsync

** Rsyncer

Copy files and folders from source to target

#+begin_src fish :noweb-ref rsyncer-function
function rsyncer 
    set options "dryrun"
    argparse --move-unknown --max-args 2 --min-args 2 $options -- $argv

    echo "Source: $argv[1]"
    echo "target: $argv[2]"


    if set --query _flag_target
	echo "Target: $_flag_target"
    end

    if set --query _flag_dryrun
	echo "Dry Run"
    end
    #rsync --info=progress2 --archive --human-readable
end
#+end_src

** Rsyncerd

Convert this to [[https://fishshell.com/docs/current/cmds/argparse.html][argparse]]

#+begin_src fish :noweb-ref rsyncerd-function
function rsyncerd --argument-names SOURCE TARGET BACKUP MAX_DELETE
    # check if source is a directory
    # if a directory does it have a trailing slash
    # if it doesn't have a trailing slash, add one

    # if BACKUP was set
    # check if it's a directory
    # if not raise an error

    # check if max delete set
    # if so add the option
    rsync  --verbose   --info=progress2 --archive --delete  --human-readable --backup --backup-dir=/tmp/backup/--max-delete=50 --dry-run SOURCE TARGET
end
#+end_src

** Rsyncerf

Creates the folder structure but doesn't copy the files over.

#+begin_src fish :noweb-ref rsyncerf
abbr --add -- rsyncerf 'rsync --progress --archive --delete --include="*/" --exclude="*"'
#+end_src

** Rsyncery

Does a dry-run to show what would be done without actually transferring files. I made this because for some reason the Raspeberry Pi with Debian 11 on it has some kind of bug that makes rsync fail if the transfers take too long. I don't really know the cause, but it doesn't happen with newer ubuntu versions so it seem like either it's a bug in the creation of the LUKs drive (since I'm creating it on the Raspberry Pi) or in the running of rsync (when the error actually occurs), but in either case, I sometimes need to do sub-folders one at a time instead of just syncing the top folder in order to keep the transfers shorter and running this lets me see what folders need to be synced.

#+begin_src fish :noweb-ref rsyncery
abbr --add -- drysync "rsync --verbose --archive --delete --dry-run"
#+end_src
